name: Make a release of a specialised micropython

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref}}
  cancel-in-progress: true

jobs:
  build_micropython:
    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        include:
          - idf: v5.0.4
            experimental: false
          - idf: v5.1.3
            experimental: true
          - idf: v5.2
            experimental: true

    steps:
      - uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: build_micropython
        id: build
        run: |
          ./micropython.sh ${{ matrix.idf }}
          cat vars >> ${GITHUB_OUTPUT}
          git tag ${{ steps.build.outputs.version }}
          git push --tags
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: micropython*.bin
          tag_name: ${{ steps.build.outputs.version }}
